name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Check for updates
        run: |
          npm outdated || true
          
      - name: Update dependencies
        run: |
          npm update
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: '⬆️ Update dependencies'
          body: |
            Automated dependency updates
            
            - Dependencies were automatically updated
            - All tests have passed
            - Please review the changes before merging
          branch: dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
          draft: false 