name: Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Check for outdated dependencies
        run: npm outdated
        continue-on-error: true
        
      - name: Run security audit
        run: npm audit
        continue-on-error: true
        
      - name: Create issue for outdated dependencies
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/dependencies.md
          
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  notify:
    name: Send Report
    needs: [security, dependencies]
    runs-on: ubuntu-latest
    if: always()
    environment: production
    
    steps:
    - name: Prepare status report
      id: report
      run: |
        echo "### Maintenance Run Report" > report.md
        echo "- Security Checks: ${{ needs.security.result }}" >> report.md
        echo "- Dependency Updates: ${{ needs.dependencies.result }}" >> report.md
        
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1
      with:
        channel-id: ${{ secrets.PRODUCTION_SLACK_CHANNEL }}
        slack-message: |
          Weekly Maintenance Run Complete
          ${{ steps.report.outputs.content }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.PRODUCTION_SLACK_TOKEN }} 